### ISSUE TITLE
Fastlane - add images/icon.png and maybe screenshots

### ISSUE THREAD

**Issue by licaon-kter** [Andrewerr/Mirror#1]

**Comment by Andrewerr** [comment]
Hello. Thank you for suggestion! I would definitely add icon to fastlane. Though not sure that I would be able to do any screenshots which looks good due to app specific

**Comment by licaon-kter** [comment]
Anything helps, maybe a toy character? :)

**Comment by Andrewerr** [comment]
Hmm. I have got a pillow in form of Pusheen the Cat, so I guess I can use it for creating a screenshot :)
